# Generated by Django 5.2 on 2026-01-15 01:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='id de la boutique'),
            preserve_default=False,
        ),
    ]
