# Generated by Django 5.2 on 2026-01-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_shop_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
