# Generated by Django 5.2 on 2026-01-17 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='Nom de la boutique')),
                ('shop_category', models.CharField(choices=[('fashion', 'Mode & Vêtements'), ('electronics', 'Électronique'), ('food', 'Alimentation & Boissons'), ('beauty', 'Beauté & Cosmétiques'), ('home', 'Maison & Jardin'), ('sports', 'Sports & Fitness'), ('books', 'Livres & Fournitures'), ('toys', 'Jouets & Jeux'), ('jewelry', 'Bijoux & Accessoires'), ('health', 'Santé & Bien-être'), ('automotive', 'Automobile'), ('arts', 'Art & Artisanat'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('wa_num', models.CharField(max_length=20, verbose_name='Numéro WhatsApp')),
                ('location', models.CharField(max_length=100, verbose_name='Localisation')),
                ('shop_id', models.CharField(max_length=100, verbose_name='id de la boutique')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=50, verbose_name='Catégorie')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('price', models.CharField(max_length=10, verbose_name='prix du produit')),
                ('can_negotiate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop', verbose_name='Boutique')),
            ],
        ),
    ]
