# Generated by Django 5.2 on 2026-01-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='can_negotiate',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='O', max_length=16, verbose_name='prix du produit'),
        ),
    ]
