# Generated by Django 5.2 on 2026-01-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_can_negotiate_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.JSONField(default=list),
        ),
    ]
