# Generated by Django 5.2 on 2026-01-28 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shophistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='old_shop_name',
        ),
        migrations.AddField(
            model_name='shophistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shophistory',
            name='old_shop_id',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=100, verbose_name='Ancien identifiant de la boutique'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='0', max_length=16, verbose_name='Prix du produit'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Identifiant public de la boutique'),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shop.shop', verbose_name='Boutique actuelle'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Image du produit')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
        ),
    ]
