# Generated by Django 5.2 on 2026-01-28 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shophistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shophistory',
            name='old_shop_id',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='shophistory',
            name='old_shop_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='O', max_length=16, verbose_name='prix du produit'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(max_length=100, verbose_name='id de la boutique'),
        ),
        migrations.AlterField(
            model_name='shophistory',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop', verbose_name='Boutique'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
