# Generated by Django 5.2 on 2026-02-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shophistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_category',
            field=models.CharField(choices=[('fashion', 'Mode & Vêtements'), ('digital', 'Produit digital'), ('electronics', 'Électronique'), ('food', 'Alimentation & Boissons'), ('beauty', 'Beauté & Cosmétiques'), ('home', 'Maison & Jardin'), ('sports', 'Sports & Fitness'), ('books', 'Livres & Fournitures'), ('toys', 'Jouets & Jeux'), ('jewelry', 'Bijoux & Accessoires'), ('health', 'Santé & Bien-être'), ('automotive', 'Automobile'), ('arts', 'Art & Artisanat'), ('other', 'Autre')], max_length=20, verbose_name='Catégorie'),
        ),
    ]
